### ISSUE TITLE
autoplot.PredictionRegr type xy, residual plot instead?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3viz#15]
The current autoplot for regression generates this plot:
```r
library(mlr3)
library(mlr3learners)
library(mlr3viz)
task3 = tsk("boston_housing")
learner = lrn("regr.ranger", min.node.size = 50)$train(task3)
p = learner$predict(task3)
autoplot(p)
```
![image](https://user-images.githubusercontent.com/1888623/72911520-83fcc600-3d3a-11ea-8220-6ab337bd4939.png)
but the following would be more helpful:
![image](https://user-images.githubusercontent.com/1888623/72911815-f9689680-3d3a-11ea-896b-b4d13b1df900.png)

Is there any advantage of the plot above to the suggested one? The only one I can think of is that the latter is a tiny bit harder to understand. But if we want to keep the first one we should at least add a `y=x` line.

**Comment by mllg** [comment]
1. We can also have a residual plot, sure. But maybe just additionally? I find the first plot easier to interpret.
2. Not sure why you have truth on the x, IIRC `plot.lm()` has response on x.
3. Having `g(x) = x` in there sounds good.

**Comment by jakob-r** [comment]
1. Ok, but I wanted to avoid additional code (although its just three lines) and I didn't see any advantage of the xy plot.
2. You are right. I will change that.
3. Will do.
