### ISSUE TITLE
plot for feature importance

### ISSUE THREAD

**Issue by kapsner** [mlr-org/mlr3viz#26]
Would it be possible to add a plot to visualize feature importances?

I have created such a function [here](https://github.com/mlr3learners/mlr3learners.lightgbm/blob/master/R/importance_plot.R), that takes the named feature importance vector and returns a barplot.

**Comment by pat-s** [comment]
Feature importance is a large field and when making a default plot for it we make a subjective decision on what feature importance is - which inexperienced users might take as "the solution". So not sure if we should do this.

Also FI returns are learner specific and cannot be faceted therefore.
But maybe I am thinking too restrictively here and we should just do it :)

**Comment by kapsner** [comment]
> Also FI returns are learner specific and cannot be faceted therefore.

I am no expert with FI, however, my assumption was, if they can be automatically tested within the mlr3-pipeline, they need somehow to be formatted in the same manner across all mlr3-learners and consequently can also be displayed in a similar manner.
Maybe it was by chance, but the unit tests for `mlr3learnes.lightgbm` initially failed when returning the native lightgbm-FI. When transforming them to a named vector, unit tests ran successfully.

**Comment by jakob-r** [comment]
The intention of our plot functions is that they are either basic plot functions for some of our mlr3 classes/objects or that they implement visualizations that are often needed but not simple to code.

Feature Importance is just a numeric vector, so it does not fall into the first category.
As a numeric vector I can just call `barplot(l$importance())` so it does not fall into the second category either.
If you want modifications then we are again following a subjective point of view as @pat-s pointed out. This we also want to avoid.

OT: Regarding your lightgbm implementaion: I don't know if it is actually a good idea to include any functions that are not entirely necessary for the learner into the learner package. 
And also: Probably yes. Our tests should check that the importance values are properly named.

I would close this issue if there is not big protest.

**Comment by kapsner** [comment]
> Feature Importance is just a numeric vector, so it does not fall into the first category.
As a numeric vector I can just call barplot(l$importance()) so it does not fall into the second category either.

Yes, you are right. Thanks for your reply anyway! So I am closing this issue.
