### ISSUE TITLE
Move ggplot2 to Depends?

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3viz#3]
Currently I need to load _ggplot2: before `autoplot()` will be available.

I assume that all functions will use `ggplot2` in the background anyways? Having it in Depends would trigger an auto-load when loading _mlr3viz_.

**Comment by berndbischl** [comment]
agree this is probably reasonable here

**Comment by mllg** [comment]
It would also be possible to re-export `autoplot` and `fortify`, like I did for `as.data.table()` in mlr3: https://github.com/mlr-org/mlr3/blob/master/R/reexports.R

Would that suffice?

**Comment by berndbischl** [comment]
but why not depends? you are kinda immediatly calling ggplot2 fuinctions as a user, right?
not that i care that much....

**Comment by pat-s** [comment]
I know that Depends is a "hot thing" but in this case.
I also do not care that much unless I do not load ggplot2 by hand 🖐️ 🙂

**Comment by mllg** [comment]
`ggplot2` exports ~400 objects, ~450 in the devel version. I'm just trying to avoid future namespace conflicts.

**Comment by mllg** [comment]
57edd3d re-exports `autoplot()` and `fortify()`. No need to attach `ggplot2` unless you want to customize some of the returned plots.

**Comment by pat-s** [comment]
If we add more complex visualizations in the future, would loading `ggplot2` not become unavoidable at some point?

**Comment by mllg** [comment]
We are loading `ggplot2` (it is in `Imports`, not `Suggests`), we are just not attaching the namespace to the user's search path.

**Comment by pat-s** [comment]
ok :+1:
