### ISSUE TITLE
plot function for learners

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3viz#4]
each learner should allow a simple plot function in its API
this should be an s3 method plot.class in mlr3viz
the function displays a "standard view" of the model, in ggplot or base R plot or ....
if some creates a local learner or a learner in the mlr3 learners online repo, this function
can also be defined locally / there

**Comment by mllg** [comment]
Maybe we can discuss this shortly during the sprint. I'll open separate issues for each "recommended" learner so we can discuss things.
