### ISSUE TITLE
autoplot plots on all data instead of subset

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3viz#5]
Autoplot always uses all observations, despite how much we filter etc.
```r
tsk = mlr_tasks$get("iris")
autoplot(tsk$clone()$filter(1:5), type = "pairs")
```

**Comment by mllg** [comment]
Cannot reproduce. Can you check again that your MWE works?

**Comment by pfistfl** [comment]
I tried and also do not seem able to reproduce. 
Will reopen once I can.
