### ISSUE TITLE
roc curves with mlr3::autoplot() for benchmark with “holdout” resampling

### ISSUE THREAD

**Issue by missuse** [mlr-org/mlr3viz#54]
Hi,

[This SO question](https://stackoverflow.com/questions/64424267/roc-curves-with-mlr3autoplot-for-benchmark-with-holdout-resampling) highlights a problem with autoploting ROC curves from benchmark result when holdout is used.

If needed I can copy the example here?

All the best,

Milan

**Comment by mllg** [comment]
Thanks for reporting, now fixed.
