### ISSUE TITLE
ROC curve for `PredictionClassif` objects switches the classes.

### ISSUE THREAD

**Issue by missuse** [mlr-org/mlr3viz#75]
Hi there,

consider the following example from the book: https://mlr3book.mlr-org.com/binary-classification.html

```
library(mlr3)
library(mlr3viz)


data("Sonar", package = "mlbench")
task = as_task_classif(Sonar, target = "Class", positive = "R")

sum(Sonar$Class == "R") #97 instances of positive class
#> [1] 97

learner = lrn("classif.rpart", predict_type = "prob")
pred = learner$train(task)$predict(task)

pred$confusion #87/97
#>         truth
#> response  R  M
#>        R 87 16
#>        M 10 95

pred$score(msr("classif.sensitivity"))
#> classif.sensitivity 
#>           0.8969072

autoplot(pred, type = "roc")
```
![roc](https://user-images.githubusercontent.com/35730264/124151016-6769cf00-da92-11eb-929b-0e71a66a1b88.png)

`Created on 2021-07-01 by the reprex package (v2.0.0)`

While there are 97 instances of the positive class, the roc curve plot suggests there are 111 instances of the positive class because it treats the negative class as the positive.

I think the problem is in the `mlr3viz:::roc_data` function, specifically the line 

 `data.table(scores = prediction$prob[, 2L], labels = prediction$truth)`

which implies the second column of the `prob` slot is the positive class, however in `PredictionClassif` objects the first column corresponds to the positive class:

`head(pred$prob)`
#output
```
             R         M
[1,] 0.8939394 0.1060606
[2,] 0.2666667 0.7333333
[3,] 1.0000000 0.0000000
[4,] 0.8939394 0.1060606
[5,] 0.0750000 0.9250000
[6,] 1.0000000 0.0000000
```

This is most likely related to: https://github.com/mlr-org/mlr3viz/issues/72

Thank you,

Milan

**Comment by mllg** [comment]
Thanks for the detailed report! I've updated the score extraction and now also explicitly specify the positive class. Your example and also #72 seem to be fixed via ab955ed .

**Comment by mllg** [comment]
@be-marc do you have a good idea how to write a test for this?

**Comment by mllg** [comment]
I'll use vdiffr to test this.
