### ISSUE TITLE
ROC curve for PredictionClassif objects switches the classes

### ISSUE THREAD

**Issue by FionaKunz** [mlr-org/mlr3viz#77]
This issue is related to: #72 #75 

I am not sure if the problem is really fixed? At least I still get the ROCs under the bisector after reinstalling the mlr3viz-package as well as using the development version?

Moreover, the example in the documentation might have to be updated:
[https://mlr3viz.mlr-org.com/reference/autoplot.BenchmarkResult.html
](url)

**Comment by mllg** [comment]
You are right, I've discovered more problems. I hope that #79 (included in today's release) now works fine. Please reopen if something is still odd.
